/*
 * Decompiled with CFR 0_115.
 */
package com.google.android.gms.b;

import com.google.android.gms.ads.internal.g;
import com.google.android.gms.b.ae;
import com.google.android.gms.b.fi;
import java.util.List;
import java.util.concurrent.TimeUnit;

@fi
public final class an {
    public static final ae A;
    public static final ae B;
    public static final ae C;
    public static final ae D;
    public static final ae E;
    public static final ae F;
    public static final ae G;
    public static final ae H;
    public static final ae I;
    public static final ae J;
    public static final ae K;
    public static final ae L;
    public static final ae M;
    public static final ae N;
    public static final ae O;
    public static final ae P;
    public static final ae Q;
    public static final ae R;
    public static final ae S;
    public static final ae T;
    public static final ae U;
    public static final ae V;
    public static final ae W;
    public static final ae X;
    public static final ae Y;
    public static final ae Z;
    public static final ae a;
    public static final ae aA;
    public static final ae aB;
    public static final ae aC;
    public static final ae aD;
    public static final ae aE;
    public static final ae aF;
    public static final ae aG;
    public static final ae aa;
    public static final ae ab;
    public static final ae ac;
    public static final ae ad;
    public static final ae ae;
    public static final ae af;
    public static final ae ag;
    public static final ae ah;
    public static final ae ai;
    public static final ae aj;
    public static final ae ak;
    public static final ae al;
    public static final ae am;
    public static final ae an;
    public static final ae ao;
    public static final ae ap;
    public static final ae aq;
    public static final ae ar;
    public static final ae as;
    public static final ae at;
    public static final ae au;
    public static final ae av;
    public static final ae aw;
    public static final ae ax;
    public static final ae ay;
    public static final ae az;
    public static final ae b;
    public static final ae c;
    public static final ae d;
    public static final ae e;
    public static final ae f;
    public static final ae g;
    public static final ae h;
    public static final ae i;
    public static final ae j;
    public static final ae k;
    public static final ae l;
    public static final ae m;
    public static final ae n;
    public static final ae o;
    public static final ae p;
    public static final ae q;
    public static final ae r;
    public static final ae s;
    public static final ae t;
    public static final ae u;
    public static final ae v;
    public static final ae w;
    public static final ae x;
    public static final ae y;
    public static final ae z;

    static {
        a = ae.a(0, "gads:sdk_core_experiment_id");
        b = ae.a(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
        c = ae.a(0, "gads:request_builder:singleton_webview", false);
        d = ae.a(0, "gads:request_builder:singleton_webview_experiment_id");
        e = ae.a(0, "gads:sdk_use_dynamic_module", false);
        f = ae.a(0, "gads:sdk_use_dynamic_module_experiment_id");
        g = ae.a(0, "gads:sdk_crash_report_enabled", false);
        h = ae.a(0, "gads:sdk_crash_report_full_stacktrace", false);
        i = ae.a(0, "gads:block_autoclicks", false);
        j = ae.a(0, "gads:block_autoclicks_experiment_id");
        k = ae.b(0, "gads:prefetch:experiment_id");
        l = ae.a(0, "gads:spam_app_context:experiment_id");
        m = ae.a(0, "gads:spam_app_context:enabled", false);
        n = ae.a(0, "gads:video_stream_cache:experiment_id");
        o = ae.a(0, "gads:video_stream_cache:limit_count", 5);
        p = ae.a(0, "gads:video_stream_cache:limit_space", 8388608);
        q = ae.a(0, "gads:video_stream_exo_cache:buffer_size", 8388608);
        r = ae.a(0, "gads:video_stream_cache:limit_time_sec", 300);
        s = ae.a(0, "gads:video_stream_cache:notify_interval_millis", 1000);
        t = ae.a(0, "gads:video_stream_cache:connect_timeout_millis", 10000);
        u = ae.a(0, "gads:video:metric_reporting_enabled", false);
        v = ae.a(0, "gads:video:metric_frame_hash_times", "");
        w = ae.a(0, "gads:video:metric_frame_hash_time_leniency", 500);
        x = ae.b(0, "gads:spam_ad_id_decorator:experiment_id");
        y = ae.a(0, "gads:spam_ad_id_decorator:enabled", false);
        z = ae.b(0, "gads:looper_for_gms_client:experiment_id");
        A = ae.a(0, "gads:looper_for_gms_client:enabled", true);
        B = ae.a(0, "gads:sw_ad_request_service:enabled", true);
        C = ae.a(0, "gads:sw_dynamite:enabled", true);
        D = ae.a(0, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
        E = ae.a(0, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
        F = ae.a(0, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
        G = ae.a(0, "gads:enabled_sdk_csi", false);
        H = ae.a(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
        I = ae.a(0, "gads:sdk_csi_write_to_file", false);
        J = ae.a(0, "gads:enable_content_fetching", true);
        K = ae.a(0, "gads:content_length_weight", 1);
        L = ae.a(0, "gads:content_age_weight", 1);
        M = ae.a(0, "gads:min_content_len", 11);
        N = ae.a(0, "gads:fingerprint_number", 10);
        O = ae.a(0, "gads:sleep_sec", 10);
        P = ae.a(0, "gad:app_index_enabled", true);
        Q = ae.a(0, "gads:app_index:without_content_info_present:enabled", true);
        R = ae.a(0, "gads:app_index:timeout_ms", 1000);
        S = ae.a(0, "gads:app_index:experiment_id");
        T = ae.a(0, "gads:kitkat_interstitial_workaround:experiment_id");
        U = ae.a(0, "gads:kitkat_interstitial_workaround:enabled", true);
        V = ae.a(0, "gads:interstitial_follow_url", true);
        W = ae.a(0, "gads:interstitial_follow_url:register_click", true);
        X = ae.a(0, "gads:interstitial_follow_url:experiment_id");
        Y = ae.a(0, "gads:analytics_enabled", true);
        Z = ae.a(0, "gads:ad_key_enabled", false);
        aa = ae.a(0, "gads:webview_cache_version", 0);
        ab = ae.b(0, "gads:pan:experiment_id");
        ac = ae.a(0, "gads:native:engine_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
        ad = ae.a(0, "gads:ad_manager_creator:enabled", true);
        ae = ae.a(1, "gads:interstitial_ad_pool:enabled", false);
        af = ae.a(1, "gads:interstitial_ad_pool:schema", "customTargeting");
        ag = ae.a(1, "gads:interstitial_ad_pool:max_pools", 3);
        ah = ae.a(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
        ai = ae.a(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
        aj = ae.a(1, "gads:interstitial_ad_pool:experiment_id");
        ak = ae.a(0, "gads:log:verbose_enabled", false);
        al = ae.a(0, "gads:device_info_caching:enabled", true);
        am = ae.a(0, "gads:device_info_caching_expiry_ms:expiry", 300000);
        an = ae.a(0, "gads:gen204_signals:enabled", false);
        ao = ae.a(0, "gads:webview:error_reporting_enabled", false);
        ap = ae.a(0, "gads:adid_reporting:enabled", false);
        aq = ae.a(0, "gads:ad_settings_page_reporting:enabled", false);
        ar = ae.a(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", false);
        as = ae.a(0, "gads:request_pkg:enabled", true);
        at = ae.a(0, "gads:gmsg:disable_back_button:enabled", false);
        au = ae.a(0, "gads:network:cache_prediction_duration_s", 300);
        av = ae.a(0, "gads:mediation:dynamite_first:admobadapter", true);
        aw = ae.a(0, "gads:mediation:dynamite_first:adurladapter", true);
        ax = ae.a(0, "gads:ad_loader:timeout_ms", 60000);
        ay = ae.a(0, "gads:rendering:timeout_ms", 60000);
        az = ae.a(0, "gads:adshield:enable_adshield_instrumentation", false);
        aA = ae.a(0, "gass:enabled", false);
        aB = ae.a(0, "gass:enable_int_signal", true);
        aC = ae.a(0, "gads:adid_notification:first_party_check:enabled", true);
        aD = ae.a(0, "gads:edu_device_helper:enabled", true);
        aE = ae.a(0, "gads:support_screen_shot", true);
        aF = ae.a(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
        aG = ae.a(0, "gads:custom_render:ping_on_ad_rendered", false);
    }

    public static List a() {
        return g.h().a();
    }
}

